ref #781 remove and mark old blacklist handling as deprecated
chameleon-system/chameleon-base pull request #642
Opened 2022-06-13 07:50 UTC by pSpeck

| Q             | A
| ------------- | ---
| Branch        | 7.1.x
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed issues  | chameleon-system/chameleon-system#781
| License       | MIT

2022-06-13 08:59 UTC, rnuernberg requested changes

2022-06-13 08:59 UTC, rnuernberg commented on src/CoreBundle/private/library/classes/TCMSTableEditor/TCMSTableEditorEndPoint.class.php
> -            $_SESSION[self::DELETE_BLACKLIST_SESSION_VAR] = array();
Please also mark the constant `DELETE_BLACKLIST_SESSION_VAR` as deprecated.

2022-06-13 09:15 UTC, rnuernberg approved these changes

2022-06-13 09:15 UTC, merged

2022-07-21 10:43 UTC, UlrichKu commented on src/CoreBundle/private/library/classes/TCMSTableEditor/TCMSTableEditorEndPoint.class.php
>      public function IsInDeleteBlackList($sTableId = false, $sRecordId = false)
As we now know that this always returns false we should also remove the call in IsAllowedDelete().